# This workflow will:
# 1. Run unit and functional tests on the code
# 2. Build the docker image and test the docker image before pushing it to a dockerhub repository
# 3. Deploy the application to AWS using Elastic Beanstalk.

name: Build-Test-Deploy

on:
  push:
    branches: [ main ]
jobs:

  # First Job: Build the project and run the tests
  build-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        python -m pytest
        
    - name: Print job completion message
      run: echo "Code built and tested successfully." 
   
  # Second job: build and test docker image and if successfuly built, push it to a dockerhub repository
  docker-image:
    runs-on: ubuntu-latest
    needs: [build-test]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker image
        run: docker build --tag taskmaster:latest .
        
      - name: Test the image
        run: |
          # Run the docker container
          docker run -t -d --name taskmaster_container -p 5000:5000 taskmaster:latest
          # Confirm that the container is actually running by executing a command on it. 
          # A running container will respond with a list of the content of its working directory. 
          # Executing "exec" on a container that's not running will raise an Error response from daemon
          docker exec taskmaster_container ls  
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
          tags: task-master-latest-${{ github.run_number}}
          
      - name: Print job completion message
        run: echo "Docker image built successfully. Container runs." 
          
  # Third job: deploy to aws
  deploy:
      runs-on: ubuntu-latest
      needs: [docker-image]

      steps:

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r taskmaster-app-${{ github.sha }}.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16 
        with:
          aws_access_key: ${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.ACTIONS_AWS_SECRET_ACCESS_KEY }}
          application_name: taskmaster
          environment_name: Taskmaster-env
          version_label: ${{ github.sha }}
          region: eu-west-2
          deployment_package: taskmaster-app-${{ github.sha }}.zip
        

  

   
   
   

